name: Weekly DB Update

on:
  schedule:
    - cron: '0 0 * * 0'   # كل أسبوع
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install libs
        run: pip install --no-cache-dir -r requirements.txt

      - name: Debug files
        run: |
          echo "Current dir:"
          pwd
          echo "List data folder:"
          ls -R data || echo "no data folder" 
          
      - name: Run DB builder
        run: python build_db_app.py || echo "build failed"
    
      - name: Commit changes
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "auto update db" || echo "no changes"
          git push
